### ISSUE TITLE
how can i change the rabbitmq ip from localhost to my docker-machine ip

### ISSUE THREAD

**Issue by jnuc093** [hipster-labs/generator-jhipster-spring-cloud-stream#24]
since my docker-machine ip is '192.168.99.100' , how can i change the RabbitMQ ip to the 'docker-machine ip'

➜  ~ docker-machine ip
192.168.99.100

> 
2018-02-24 22:30:07.621  WARN 5645 --- [q_iWh6Lr_SYA-51] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it. Exception summary: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "jrabit",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "35bfb0fc8fdb9081a1fd1e1f7120de2c50d464ea",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  },
  "generator-jhipster-spring-cloud-stream": {
    "promptValues": {
      "messageBrokerType": "RabbitMQ",
      "rabbitMqNameOfMessage": "message"
    }
  }
}

**Comment by pascalgrimaud** [comment]
Indeed, it's an interesting question, specially in Production.
Honestly, I don't have the answer, I need to look the official documentation.

But in your case, as you are in Dev, you should look this tips:
http://www.jhipster.tech/tips/020_tip_using_docker_containers_as_localhost_on_mac_and_windows.html

It's a must have, as you use docker-machine

**Comment by vcupelloni** [comment]
@jnuc093 have you found a way to change the rabbitmq ip configuration?

I've tried reading documentation:

[https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#multiple-systems](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#multiple-systems
)
```
spring:
    cloud:
      stream:
        bindings:
          input:
              destination: thing1
              binder: rabbit1
          output:
              destination: thing2
              binder: rabbit2
        binders:
            rabbit1:
              type: rabbit
              environment:
                  spring:
                      rabbitmq:
                          host: <host1>
```
But at boot it always try to connect to a local istance of RabbitMQ...any ideas?
