### ISSUE TITLE
Support on Queue creation

### ISSUE THREAD

**Issue by flefevre** [hipster-labs/generator-jhipster-spring-cloud-stream#29]
Dear generator-jhipster-spring-cloud-stream team,
I have some questions on how to configure the project, where is the good place to ask?

I wanted to be able to create my queue with a given name, add binding etc... but I do not see how to do it?

do i have to do it here:
public class CloudMessagingConfiguration extends AbstractCloudConfig

or in the src/main/resources/config/application-dev.yml
but no way to precise the queue naming

Thanks for your help / advice.

```
    cloud:
        stream:
            default:
                contentType: application/json
            # bindings:
            #     input:
            #         destination: topic-jhipster
            #     output:
            #         destination: topic-jhipster
```
